### ISSUE TITLE
Website URL returns 404

### ISSUE THREAD

**Issue by CodeFluent** [PantherHackers/recruiting_page#1]
I thought that making gh-pages default would solve it, but apparently it did not. 

[PantherHackers.github.io/recruiting](PantherHackers.github.io/recruiting) just returns a 404 at the URL: [pantherhackers.github.io](pantherhackers.github.io). 

Looking at the [Github Pages documentation](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages), it says that orgname.github.io/projectname should work, but it doesn't here. 

[This](https://stackoverflow.com/questions/23554086/creating-a-github-project-page-for-a-repository-owned-by-an-organization) stackoverflow question addresses the problem also. 

I suggest that we rename the repo to PantherHackers.github.io to allow github to recognize it as an organization site. I don't see any other way where this repo can be a project site that follows a username.github.io or orgname.github.io site. Please submit suggestions however,I might have missed important things.

**Comment by badjr** [comment]
You had to create a CNAME file, which allows you to set up a custom domain. The instructions are [here](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages). I created and commited it, and the [PantherHackers.github.io/recruiting](PantherHackers.github.io/recruiting) link works now.

**Comment by CodeFluent** [comment]
Awesome cool. I thought CNAMEs were optional. I created my site without one, but I was using a framework Github liked, so it might've just been that. 

Btw, that link goes to 
https://github.com/PantherHackers/recruiting/issues/PantherHackers.github.io/recruiting instead of just the domain. You don't have to fix it, but if other people see this they might get confused.

Closing this Issue.

**Comment by badjr** [comment]
I tested it on another organization, and it appears to work if you just make a gh-pages branch. So the CNAME file probably is optional. Not sure why it didn't work before, because there was a gh-pages branch.
